// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="ResourceKeys.cs" company="Talegen">
//     Copyright (c) Talegen, LLC. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace Talegen.Linq.QueryBuilder.Models.Properties
{
    /// <summary>
    /// This class is automatically generated and will create resource keys for use within the application.
    /// </summary>
    public static class ResourceKeys
    {
        /// <summary>
        /// Gets the key for the LabelAndText resource string.
        /// </summary>
        public const string LabelAndText = "LabelAndText"; 

        /// <summary>
        /// Gets the key for the LabelContainsText resource string.
        /// </summary>
        public const string LabelContainsText = "LabelContainsText"; 

        /// <summary>
        /// Gets the key for the LabelDoesNotContainText resource string.
        /// </summary>
        public const string LabelDoesNotContainText = "LabelDoesNotContainText"; 

        /// <summary>
        /// Gets the key for the LabelDoesNotEndWithText resource string.
        /// </summary>
        public const string LabelDoesNotEndWithText = "LabelDoesNotEndWithText"; 

        /// <summary>
        /// Gets the key for the LabelDoesNotStartWithText resource string.
        /// </summary>
        public const string LabelDoesNotStartWithText = "LabelDoesNotStartWithText"; 

        /// <summary>
        /// Gets the key for the LabelEndsWithText resource string.
        /// </summary>
        public const string LabelEndsWithText = "LabelEndsWithText"; 

        /// <summary>
        /// Gets the key for the LabelNoText resource string.
        /// </summary>
        public const string LabelNoText = "LabelNoText"; 

        /// <summary>
        /// Gets the key for the LabelOrText resource string.
        /// </summary>
        public const string LabelOrText = "LabelOrText"; 

        /// <summary>
        /// Gets the key for the LabelStartsWithText resource string.
        /// </summary>
        public const string LabelStartsWithText = "LabelStartsWithText"; 

        /// <summary>
        /// Gets the key for the LabelYesText resource string.
        /// </summary>
        public const string LabelYesText = "LabelYesText"; 
    }
}
